"""
FRUITS.py

List of fruits.
"""

FRUITS = [
    'Akee',
    'Alibertia',
    'Apple',
    'Apricot',
    'Araza',
    'Avocado',
    'Bael Fruit',
    'Balckcurrant',
    'Banana',
    'Barbados Cherry',
    'Barberry',
    'Bignay',
    'Bilberry',
    'Biriba',
    'Black Sapote',
    'Blackberry',
    'Blackcurrant',
    'Blood orange',
    'Blueberry',
    'Boysenberry',
    'Breadfruit',
    "Buddha's hand (fingered citron)",
    'Calabash',
    'Canary Melon',
    'Cantaloupe',
    'Cape Gooseberry',
    'Casaba',
    'Ceylon Gooseberry',
    'Chalta',
    'Champedak',
    'Charantais',
    'Cherimoya',
    'Cherry',
    'Chico fruit',
    'Chili pepper',
    'Christmas Melon',
    'Clementine',
    'Cloudberry',
    'Coconut',
    'Corn kernel',
    'Crab apples',
    'Cranberry',
    'Crenshaw',
    'Cucumber',
    'Currant',
    'Currants',
    'Custard Apple',
    'Custard apple',
    'Damson',
    'Date',
    'Dragonfruit',
    'Durian',
    'Eggplant',
    'Elderberry',
    'Feijoa',
    'Fig',
    'Galia',
    'Gandaria',
    'Genipap',
    'Giant Granadilla',
    'Goji berry',
    'Golden Apple',
    'Gonzoberry'
    'Gooseberry',
    'Grape',
    'Grapefruit',
    'Green Pepper',
    'Guava',
    'Hogplum',
    'Honeyberry',
    'Honeydew',
    'Huckleberry',
    'Indian Jujube',
    'Ita Palm',
    'Jaboticaba',
    'Jabuticaba',
    'Jackfruit',
    'Jamaica Cherry',
    'Jambul',
    'Jujube',
    'Juniper berry',
    'Kechapi',
    'Kepel',
    'Ketupa',
    'Kiwano',
    'Kiwano (horned melon)',
    'Kiwi Fruit',
    'Kiwifruit',
    'Kumquat',
    'Leech Lime',
    'Lemon',
    'Lime',
    'Loganberry',
    'Longan',
    'Loquat',
    'Lucuma',
    'Lychee',
    'Malay Apple',
    'Mammey Apple',
    'Mammey Sapote',
    'Mandarin',
    'Mandarine',
    'Mango',
    'Mangosteen',
    'Marionberry',
    'Melon',
    'Melon-pear',
    'Minneola',
    'Miracle fruit',
    'Monkey Bread',
    'Morinda',
    'Moutain Soursop',
    'Mulberry',
    'Musk Melon',
    'Nance',
    'Nangka',
    'Nashi Pear',
    'Nectarine',
    'Net Melon',
    'Ogen Melon',
    'Olive',
    'Orange',
    'Otaheite Gooseberry',
    'Papaya',
    'Passion Fruit',
    'Passionfruit',
    'Pea',
    'Peach',
    'Peach Palm',
    'Pear',
    'Persian Melon',
    'Persimmon',
    'Philippine Roseapple',
    'Pineapple',
    'Pitahaya',
    'Plantain',
    'Plum',
    'Plumcot (or Pluot)',
    'Pomegranate',
    'Pomelo',
    'Prune (dried plum)',
    'Pummelo',
    'Pumpkin',
    'Purple mangosteen',
    'Quince',
    'Raisin',
    'Rambai',
    'Rambutan',
    'Raspberry',
    'Redcurrant',
    'Rose Apple',
    'Russian Melon',
    'Sala',
    'Salak',
    'Salal berry',
    'Salmonberry',
    'Sansapote',
    'Santoli',
    'Sapodilla',
    'Satsuma',
    'Sea Grape',
    'Sharlyn',
    'Soncoya',
    'Soursop',
    'Squash',
    'Star Apple',
    'Star Fruit',
    'Star Nut Palm',
    'Star fruit',
    'Strawberry',
    'Sugar Apple',
    'Surinam Cherry',
    'Sweet Granadilla',
    'Sweet Melon',
    'Sweetsop',
    'Tamarillo',
    'Tamarind',
    'Tangelo',
    'Tangerine',
    'Tomato',
    'Tree Tomato',
    'Ugli',
    'Ugli fruit',
    'Velvet Tamarind',
    'Voavanga',
    'Water Apple',
    'Watermelon',
    'Wax Melon',
    'Winter Melon',
    'Wood Apple',
    'Xigua',
    'Yuzu',
    'Zuchini',
]
