"""
VEGETABLES.py

List of vegetables, roots, bulbs and edible flowers.
"""

VEGETABLES = [
    'Ahipa',
    'Amaranth',
    'American groundnut',
    'Aonori',
    'Arame',
    'Arracacha',
    'Artichoke',
    'Arugula',
    'Asparagus',
    'Azuki bean',
    'Bamboo shoot',
    'Beet (greens)',
    'Beetroot',
    'Black-eyed pea',
    'Bok choy (Pak choy)',
    'Borage greens',
    'Broadleaf arrowhead',
    'Broccoli',
    'Broccoli (leaves stalks)',
    'Broccolini flowers',
    'Brussels sprouts',
    'Burdock',
    'Cabbage',
    'Camas',
    'Canna',
    'Caper',
    'Cardoon',
    'Carola',
    'Carrot',
    'Cassava',
    'Catsear',
    'Cauliflower',
    'Celeriac',
    'Celery',
    'Celtuce',
    'Chaya',
    'Chickpea',
    'Chickweed',
    'Chicory',
    'Chinese artichoke',
    'Chinese mallow',
    'Chives',
    'Collard greens',
    'Common bean',
    'Common purslane',
    'Corn salad',
    'Courgette flowers',
    'Cress',
    'Dabberlocks (Badderlocks)',
    'Daikon',
    'Dandelion',
    'Daylily',
    'Dill',
    'Dolichos bean',
    'Drumstick',
    'Dulse (Dillisk)',
    'Earthnut pea',
    'Elephant foot yam',
    'Elephant garlic',
    'Endive',
    'Ensete',
    'Fat hen',
    'Fava bean',
    'Fiddlehead',
    'Florence fennel',
    'Fluted pumpkin',
    'Galangal',
    'Garbanzo',
    'Garden rocket',
    'Garland Chrysanthemum',
    'Garlic',
    'Garlic chives',
    'Ginger',
    'Golden samphire',
    'Good King Henry',
    'Grape (leaves)',
    'Greater plantain',
    'Green bean (French bean)',
    'Guar',
    'Hamburg parsley',
    'Hijiki',
    'Horse gram',
    'Horseradish',
    'Indian pea',
    'Jerusalem artichoke',
    'Jícama',
    'Kai-lan (Gai lan)',
    'Kale',
    'Kohlrabi',
    'Komatsuna',
    'Kombu',
    'Kuka',
    'Kurrat',
    'Lagos bologi',
    "Lamb's lettuce",
    "Lamb's quarters",
    'Land cress',
    'Laver Gim',
    'Leek',
    'Lemongrass',
    'Lentil',
    'Lettuce',
    'Lima bean',
    "Lizard's tail",
    'Loroco',
    'Lotus root',
    'Malabar spinach',
    'Mallow',
    'Manchurian wild rice',
    'Mashua',
    'Melokhia',
    "Miner's lettuce (Winter purslane)",
    'Mizuna greens',
    'Moth bean',
    'Mozuku',
    'Mung bean',
    'Mustard',
    'Napa cabbage',
    'New Zealand Spinach',
    'Nopal',
    'Nori',
    'Ogonori',
    'Okra',
    'Onion',
    'Orache',
    'Paracress',
    'Parsnip',
    'Pea',
    'Pea (sprouts leaves)',
    'Peanut',
    'Pearl onion',
    'Pigeon pea',
    'Pignut',
    'Poke',
    'Potato',
    'Potato onion',
    'Prairie turnip',
    'Prussian asparagus',
    'Radicchio',
    'Radish',
    'Rapini (broccoli rabe)',
    'Ricebean',
    'Runner bean',
    'Rutabaga',
    'Salsify',
    'Samphire',
    'Scorzonera',
    'Sculpit Stridolo',
    'Sea beet',
    'Sea grape',
    'Sea kale',
    'Sea lettuce',
    'Shallot',
    "Shepherd's purse",
    'Sierra Leone bologi',
    'Skirret',
    'Snap pea (sugarsnap, mangetout)',
    'Snow pea (mangetout)',
    'Soko',
    'Sorrel',
    'Sour cabbage',
    'Soybean',
    'Spinach',
    'Spring onion (scallion)',
    'Squash blossoms',
    'Summer purslane',
    'Swede',
    'Sweet potato (Kumara)',
    'Swiss chard',
    'Taro',
    'Tarwi (Tarhui Chocho)',
    'Tatsoi',
    'Tepary bean',
    'Ti',
    'Tigernut',
    'Tree onion',
    'Turmeric',
    'Turnip',
    'Turnip greens',
    'Ulluco',
    'Urad bean',
    'Velvet bean',
    'Wakame',
    'Wasabi',
    'Water caltrop',
    'Water chestnut',
    'Water spinach',
    'Watercress',
    'Welsh onion',
    'Wheatgrass',
    'Wild leek',
    'Winged bean',
    'Yacón',
    'Yam',
    'Yao choy (Yu choy)',
    'Yardlong bean',
    'Yarrow',
]
